### PR TITLE
Clean and improve import_rawdata()

### PR DESCRIPTION
**Pull request by hsonne**
- Use lapply() and do.call(rbind, ...) to read
  and merge all files
- Check if all data frames have the same column
  names and stop with a good message if not
- This should close issue #4

---
This change is [Reviewable](https://reviewable.io/reviews/kwb-r/kwb.umberto/5)

### CODE REVIEW

**Comment by mrustl** [comment]
Please fix https://ci.appveyor.com/project/KWB-R/kwb-umberto/builds/22116253

```
> umberto7_rawdata <- kwb.umberto::import_rawdata(csv_dir = umberto7_csv_dir)
Importing csv file 'C:/Users/appveyor/AppData/Local/Temp/1\RtmpCmjcT7/Beispiel_Auswertung/Ref_High_C+N.csv'
Error in janitor::clean_names(content) : object 'content' not found
Calls: <Anonymous> -> lapply -> FUN -> <Anonymous>
Execution halted
* checking for unstated

```

**Comment by hsonne** [comment]
should be fixed now

**Comment by mrustl** [comment]
___
*[R/import_rawdata.R, line 70 at r1](https://reviewable.io/reviews/kwb-r/kwb.umberto/5#-LXw5rrR8UhE1oRyZMoP:-LXw5rrS1FD4Z7ejRdxu:b-708un) ([raw file](https://github.com/kwb-r/kwb.umberto/blob/efffbf9bc8ff2fa392a0f118a10e99b77e556146/R/import_rawdata.R#L70)):*
> ```
> 
>   # Row-bind the data frames together
>   do.call(rbind, contents)
> ```

For performance reasons could you use data.table::rbindlist() instead?

**Comment by mrustl** [comment]
___
*[R/import_rawdata.R, line 71 at r2](https://reviewable.io/reviews/kwb-r/kwb.umberto/5#-LXzTMIh58_mbE-X4m0H:-LXzTMIi1-qEDi53Exy3:b-rumj9r) ([raw file](https://github.com/kwb-r/kwb.umberto/blob/421404526a181ceaab609d689fa76a2a64fd530f/R/import_rawdata.R#L71)):*
> ```
> 
>   # Row-bind the data frames together
>   data.table::rbindlist(contents, use.names = TRUE)
> ```

FYI. Increased performance

**Review by mrustl — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kwb-r/kwb.umberto/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mrustl** [comment]
Closes  #4 (reminder: add more tests for import_rawdata() )

**Pull request merged**
